### ISSUE TITLE
Review setup of the repo

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/sdd#1]
I've just finished moving http://www.tdwg.org/standards/116/ to this repo. The @tdwg/sdd team should review this.

Check to approve:
- [x] The README currently contains the information from http://www.tdwg.org/standards/116/. Since we want to create a snapshot (= release) of that version of the standard, only make editorial updates, before updating it to reflect recent work.
- [x] The standard has been uploaded as the html document I found at http://www.tdwg.org/standards/116/download, named `sdd-1.html`.
- [x] There is a preferred citation, but I'd like to standardize this across standards (comments welcome at https://github.com/tdwg/infrastructure/issues/32)
- [x] @gmhagedorn, I've added you the the @tdwg/sdd team. Could you invite other relevant SDD contributors to the team (using their GitHub name)? The team has admin access to this repository.

Once the above are OK, I'll create a release of the standard. From then on, work an SDD can continue in this repo and issue tracker.

**Comment by gmhagedorn** [comment]
thanks, so far ok.

how do I add users to a team?

the link to @tdwg/sdd team above gives me a 404 when I am logged in at
github

best

gregor

On 7 June 2015 at 17:15, Peter Desmet notifications@github.com wrote:

> I've just finished moving http://www.tdwg.org/standards/116/ to this
> repo. The @tdwg/sdd https://github.com/orgs/tdwg/teams/sdd team should
> review this.
> 
> Check to approve:
> -  The README currently contains the information from
>   http://www.tdwg.org/standards/116/. Since we want to create a snapshot
>   (= release) of that version of the standard, only make editorial updates,
>   before updating it to reflect recent work.
> -  The standard has been uploaded as the html document I found at
>   http://www.tdwg.org/standards/116/download, named sdd-1.html.
> -  There is a preferred citation, but I'd like to standardize this
>   across standards (comments welcome at tdwg/infrastructure#32
>   https://github.com/tdwg/infrastructure/issues/32)
> -  @gmhagedorn https://github.com/gmhagedorn, I've added you the the
>   @tdwg/sdd https://github.com/orgs/tdwg/teams/sdd team. Could you
>   invite other relevant SDD contributors to the team (using their GitHub
>   name)? The team has admin access to this repository.
> 
> Once the above are OK, I'll create a release of the standard. From then
> on, work an SDD can continue in this repo and issue tracker.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdwg/sdd/issues/1.

## 

---

Dr. G. Hagedorn
+49 (0)30 2093 8576 (work)
+49-(0)30-831 5785 (private)
gregor.hagedorn@mfn-berlin.de
http://www.linkedin.com/in/gregorhagedorn

This communication, together with any attachments, is made entirely on my
own behalf and in no way should be deemed to express official positions of
my employer. It is intended only for the person(s) to whom it is addressed.
Redistributing or publishing it without permission may be a violation of
copyright or privacy rights.

**Comment by peterdesmet** [comment]
You should have received an invitation to the team in your email inbox linked to your GitHub account. Once you accept the invitation, you should see the page and a box to add more team members.

**Comment by gmhagedorn** [comment]
Sorry i did not receive sich a mail, i checked spam...

G.
Am 07.06.2015 23:15 schrieb "Peter Desmet" notifications@github.com:

**Comment by peterdesmet** [comment]
Hi Gregor, I've just invited you again (at @gmhagedorn). If you don't receive an email at the address linked to that account, can you just log in on GitHub and check if you see an invitation at https://github.com/notifications or https://github.com/tdwg?

**Comment by peterdesmet** [comment]
I've updated the preferred citation to fit with the standard preferred citation for TDWG standards:

> Hagedorn G., Thiele K., Morris R. & Heidorn, P.B. 2005. Structured Descriptive Data (SDD) w3c-xml-schema, Version 1.0. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/116

Will create a release now.
