### ISSUE TITLE
Document rewrite rules needed for rs.tdwg.org

### ISSUE THREAD

**Issue by mdoering** [tdwg/sdd#2]
Does SDD need to have any redirects (see tdwg/infrastructure#59) from rs.tdwg.org or any other tdwg domain?

**Comment by CynthiaParr-USDA** [comment]
Need to consult with Gregor Hagedorn most likely.

**Comment by mdoering** [comment]
SDD files are exposed as UBIO files from rs.tdwg.org as http://rs.tdwg.org/UBIF/

For example the SDD schema is available as: 
http://rs.tdwg.org/UBIF/2005/Schema/1.0/SDD.xsd

There had also been a copy on www.gbif.org, see #3

**Comment by mdoering** [comment]
I have also exposed the same files under the sdd root instead of UBIF if needed:
http://rs.tdwg.org/sdd/2005/Schema/1.0/SDD.xsd
