### ISSUE TITLE
default page is 404 with just https://sdd.tdwg.org/ ...

### ISSUE THREAD

**Issue by stanblum** [tdwg/sdd#8]
The deployment of Jekyll has a little problem.

The base URL just 404s, but displays with a fully qualified reference:
https://sdd.tdwg.org/index.html

Compare against:  

- https://sdd.tdwg.org/   >>>  404

and
- https://sdd.tdwg.org/index.md  >>> doesn't get rendered as a webpage, just displays raw file contents.

I'm not sure what's going on here.  @larsgw or @peterdesmet,  do you have any idea?

**Comment by larsgw** [comment]
https://sdd.tdwg.org/ works for me, it might be the cache?

**Comment by stanblum** [comment]
Interesting.  I refreshed a bunch of times; definitely got some of the new
stuff, but not all of it.

Anyway, yes, it's working for me now, too.

Closing...
